version: '3.7'
services:
  mongo:
    image: mongo
    container_name: sem-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: shopDEV
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
    networks:
      - ${GLOBAL_NETWORK:-mongo}

  mongo-express:
    image: mongo-express
    container_name: sem-mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - ${GLOBAL_NETWORK:-mongo_express}