@url_dev=http://localhost:3053/v1/api/

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: c2116ceea00347ced87f5531819b21391e7165736e555c5d7be86b2c5946bee11854d3c56daf6796dc0ff784f898008d83f614de54838c57c024192e6781b013

{
    "name":"Test Shop",
    "email":"test@gmail.com",
    "password":"123456"
}

### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: c2116ceea00347ced87f5531819b21391e7165736e555c5d7be86b2c5946bee11854d3c56daf6796dc0ff784f898008d83f614de54838c57c024192e6781b013

{
    
    "email":"test@gmail.com",
    "password":"123456"
}

### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: c2116ceea00347ced87f5531819b21391e7165736e555c5d7be86b2c5946bee11854d3c56daf6796dc0ff784f898008d83f614de54838c57c024192e6781b013
x-client-id:644b47d58c26bf1dec5729b6
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDRiNDdkNThjMjZiZjFkZWM1NzI5YjYiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjgyNjU1MjU0LCJleHAiOjE2ODI4MjgwNTR9.Y0WrkWtZluClPOwkQCqes-x1C1BN8lZij1HMxTKAm4OrDf94FqWhVAjzqZHuirfwWfyilgnFeXwdNZOL3nJGZRPTT0qVCPz_qjVpEZ-WjcqFW44emnwZcUt51iIWxTXdM-F_O0p8gnVv5EYRtujxC8QRR4gm6VASZ8nUI2Xz1hxvCxTraxHAkgc04i1k_YnbpxkTy47OiJZ5sqCg0bTV0zfb4GB54G1_oVR85hG4Bv2csJ__97OmWyqvsjYHe3cpQcJWE0fqAUFtt1PUXRMdHbM0zpfmFVZaM8cZK2w52c9azC4AEVg3ZUz8TMp-2SrKCWpgovEc0HiWB6kuj7q4tgduG2MGLJbicU2O8nLNJO-ciX3Wuew2gVKIKFwGrPxNk3BvgP1IeLxf1N9SIH6kSmvz4NJhbfDCDE8hFAxgExdnAALuAePEMSK2hwMOgXdXfehehlNW83o9pbQVvY3cJZykJsG7ve8Nfv7yIxKteZCrsOHrEsA75Hz8Is7AK-AKeHuYepHJOS9_Od-NfAgLw20UNZq4ae2V9Exkm27eg4F8UT3yBKc0MAXbmJFUpAvP_FLfCSdv7NBfmK9RdYw4y96CeHMjsWWvNSBIv0Y0GSMY8NC2u6Vh6Q4c5ibS5BKkHiKC21_ElINWIQimC-2xQPI_3O1hpkKDvSRhnMivNi8

{
    
    "email":"test@gmail.com",
    "password":"123456"
}

### refresh token
POST {{url_dev}}/shop/handlerRefreshToken
Content-Type: application/json
x-api-key: c2116ceea00347ced87f5531819b21391e7165736e555c5d7be86b2c5946bee11854d3c56daf6796dc0ff784f898008d83f614de54838c57c024192e6781b013
x-client-id:644b47d58c26bf1dec5729b6
x-rftoken:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDRiNDdkNThjMjZiZjFkZWM1NzI5YjYiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjgyNjU3MDE3LCJleHAiOjE2ODMyNjE4MTd9.jME1MiIXR5vekD9dIzE7EwOkayRbz7OOCddZSXKKqsG3QmZv2wHvn9Bfx_lcIsoYWXW4EP7mPebdEfWcq2M7DqNq6ek-TSyFpbHLcrZUtcptEZFl6m3oZa2_HspA3QqrvGe_0tZRAqMzz1mj0suE4Luy3XkL6uvw4DOirqvmuJP_HsbYVghyGANgNCxmfbRYkLack8AT_QY2tIqXsV_20D_JVIb_OgQ4VQc-Ly4xRLXK5Y5aL3NZGD-riGdQ-fBwH-Rfw0Oe9Et4fPyvTI4dVOWfXhkfWGFhfeYJn1FWH2w-Y2-AHLoA5s4RxEp-PmBn4BdKKYhAoaWdWKfGewnAzup1sRx7UzpbBDmX-EJFmvhpLOWDaN1Hnhr3ZMgYQWMV-Fh9MCxNCFdHIVMRX-xJutVxDoZ8eQ4CJ_vmGz4wPb8scPul3LUTKOb8IIffPiZLSLQY807eddVPxHflV1h9hnbBc9nQhwLQDbzRcx0CS_rdroptBPuadmKT-afnD-UFdDfSnToyim9d-Hq00TLqDw3BOo5SDf1-sDNuRGRoahpMk24xiXZvsVCbTHhFpHgASPacGEiKysa8qi8V3Sh1QtQpZiWrxrRZQ8YFnISgu50hsMf6k5w_crx2g2aCPeXDpis-THs3RTu7GXxoPedoEu1WW7dcdeVEoZ9z9MvdDhQ
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDRhMjc0NjExM2MwOTRjN2E0MzIwNzMiLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjgyNjUwMDE4LCJleHAiOjE2ODI4MjI4MTh9.KJYwqa1faB4zJsoEOBV65T-KLWZB7bZVwSpPlzPp7q13sG5aSIGcsFKo5scTd-s_B8YRcWWc4h8BaJOiBskBlDNNzKgw15wbcy081z3VzAJ5h7GU12G_WSTaEmJA47-4Y45kaL35bBYbk4PESEf0FL2enD8FUNBXt6-L07jMsugVJmwjgU41OjoiY006Mk_aZl35jPYdDycY5Qx2n2JrPZhaYx9PJe3wXwE0bzQyUw5o1vEgQvE3MUctHo15Pr6Dg3bIWDJGytVcp4tKxPTX21ONzsrjdFZFE_UIITOa3J1QYcjKbLLsqgzqYF54v8EZ3B2QS3_6c2AH_LLJXcLZBenXYz8VdMRbAduAsg2F-ZBmiqeNf4qmetUM6RucEiyU9xzzH9iqgkYxuYPR3W53PY-j2JxIXPCRikTrNqI6vnyYFwZBTshRuUqwJcJS4knAVGW8FbAhjxEs1DSJp4EFAAIFuQ2HVcSuI7HUnycucdBXZamuuORMim-oCclQocBVvYz2AWYweyZGP2CfFAIBSIL62lA760TM4Pv7J3mLfHJrG169yKQevU9Fv5J9OpNLh7vLiITisP4SYdq_iSYA7RpDf1Tug6a02GnQKWMumfl9eowIZmET5fAaap5041YL9dleHXH9veLWrjAszuBGrz2oWyKTZ1mgPe9YaG6rXSo
